### ISSUE TITLE
Front page aesthetic change

### ISSUE THREAD

**Issue by ylinzhi** [facebookincubator/OSM-HOT-Tasking-Manager#233]
<img width="1041" alt="Screen Shot 2021-10-27 at 9 35 54 AM" src="https://user-images.githubusercontent.com/35787039/139127587-b57d2185-966b-4e44-90e0-b287807ecf34.png">

Adjust color combination of dark font in the magenta background on top of white layer

**Comment by zlavergne** [comment]
Closed in #240
