### ISSUE TITLE
File Size Limit Increase For Project Creation

### ISSUE THREAD

**Issue by ylinzhi** [facebookincubator/OSM-HOT-Tasking-Manager#253]
Increase current uploading file size limit from 1MB to 5MB when creating new projects from files

**Comment by tsmock** [comment]
Done in https://github.com/facebook/OSM-HOT-Tasking-Manager/pull/268/commits/27848e4aa43cbb9076e21c60ed5bd4da04540b95. This is technically a config value, so it probably should have been done in https://github.com/facebook/OSM-HOT-Tasking-Manager/blob/develop/scripts/aws/cloudformation/tasking-manager.template.js instead.
